### 01. numpy란?
#### 계산 작업을 편하게 해줄 도구
- 데이터 분석은 많은 양의 데이터로 계산을 해야함..
    - 그러려면, 파이썬으로하면 많은 코드를 짜야함
- numpy를 사용하면 그 계산이 쉬워짐!
    - 행렬, 2차원 배열 할 때 진가를 발휘한다.
    - 반복문을 쓰지 않고 리스트 안의 데이터를 한 번에 분석할 수 있다.

### 02. numpy array의 생김새

In [4]:
import numpy as np

array1 = np.array([1,2,3,4,5,6])
array1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(array1)

# ndarray : n-차원(dimension)배열

numpy.ndarray

In [6]:
# array의 형태 확인
array1.shape

# 결과값에 ,로 빈칸이 있음 => 1차원이라서 그럼

(6,)

In [7]:
# array에 몇 개의 요소가 있는지 확인
array1.size

6

### 2차원 array => 행렬에서 다시
#### array 안에 리스트가 있는 경우

In [8]:
array2 = np.array([[1,2], [3,4], [5,6]])
array2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
type(array2)

numpy.ndarray

In [10]:
array2.shape
# 3행 2열

(3, 2)

In [11]:
array2.size
# 2차원 : 3* 2 = 6 이 된다.

6

cf. 3차원 array : array안에 array가 있는데 그 안에 또 array가 있을 때

### 03. numpy array를 만드는 다양한 방법

In [12]:
# 파이썬 리스트를 통해 생성
# numpy 모듈의 array 메소드에 파라미터로 파이썬 리스트를 넘겨주면 numpy array가 리턴됩니다.

array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
    
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [13]:
# 균일한 값으로 생성 
# numpy 모듈의 full 메소드를 사용하면, 모든 값이 같은 numpy array를 생성할 수 있습니다.

array1 = np.full(6, 7)
    
print(array1)

[7 7 7 7 7 7]


In [14]:
# 모든 값이 0인 numpy array 생성
# 모든 값이 0인 numpy array를 생성하기 위해서는 full 메소드를 사용하면 되겠죠. 하지만 사실은 더 간편한 방법이 있습니다.

array1 = np.full(6, 0)
array2 = np.zeros(6, dtype=int)
    
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [15]:
# 랜덤한 값들로 생성
# 어쩔 때는 임의의 값들로 배열을 생성시키고 싶습니다. 그럴 때는 numpy의 random 모듈의 random 함수를 사용하면 됩니다.

# numpy 모듈 안에 random이라는 모듈이 있고, 그 안에 또 random이라는 함수가 있는 겁니다!
array1 = np.random.random(6)
array2 = np.random.random(6)
    
print(array1)
print()
print(array2)

[0.8355236  0.08309476 0.14890601 0.88752598 0.31719947 0.14341122]

[0.91302018 0.06137908 0.67845882 0.91353963 0.3808374  0.37766275]


In [16]:
# 연속된 값들이 담긴 numpy array 생성
# numpy 모듈의 arange 함수를 사용하면 연속된 값들이 담겨 있는 numpy array를 생성할 수 있습니다.

# arange 함수는 파이썬의 기본 함수인 range와 굉장히 비슷한 원리로 동작하는데요. 파라미터가 1개인 경우, 2개인 경우, 3개인 경우 모두 살펴봅시다.

# 파라미터 1개 
# arange(m)을 하면 0부터 m-1까지의 값들이 담긴 numpy array가 리턴됩니다.
array1 = np.arange(6)
print(array1)

[0 1 2 3 4 5]


In [17]:
# 파라미터 2개
# arange(n, m)을 하면 n부터 m-1까지의 값들이 담긴 numpy array가 리턴됩니다.

array1 = np.arange(1,4)
print(array1)

[1 2 3]


In [18]:
# 파라미터 3개
# arange(n, m, s)를 하면 n부터 m-1까지의 값들 중 간격이 s인 값들이 담긴 numpy array가 리턴됩니다.

array1 = np.arange(1,5,2)
print(array1)

[1 3]


### 04. 모듈 별명 지어주기 'as'

In [19]:
import numpy as np

array1 = np.full(6,0)
array1

array([0, 0, 0, 0, 0, 0])

### 05. numpy array 생성 연습 1

In [20]:
import numpy as np

arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### 06. numpy array 생성 연습 2

In [21]:
# 1이 꼭 포함되어야 한다는 뜻이 아니었던...
arr = np.arange(3,101,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### 07. 인덱싱, 슬라이싱

In [25]:
# 리스트 인덱싱과 동일

#특이점
#리스트로 인덱싱 - 각 인덱스에 맞는 요소가 출력됨
arr[[1,3,5]]

array([ 6, 12, 18])

In [26]:
# 리스트 슬라이싱과 동일

### 08. numpy 기본 연산
#### 계산툴 답게, array 조작이 매우 간편!!

In [37]:
array1 = np.arange(10)
array2 = np.arange(10,20)

#### 연산을 한다고 바로저장 -> X
#### 저장을 원하면 변수에 다시 담아야 한다.

In [38]:
# 각 원소에 더하고, 곱하고, 나누고 싶을 때 (numpy 안쓰던 리스트에서는 for문을 썼던...)
print(array1 * 2)
print(array1 / 2)
print(array1 + 2)

[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 2  3  4  5  6  7  8  9 10 11]


In [39]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
array1 *= 2
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
# array 끼리 연산하고 싶을 때(더하기, 나누기 모두 동일)
# 같은 인덱스에 있는 원소끼리 연산됨
array1 + array2

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

### 09. [실습] 신주쿠 흥부부대찌개

In [48]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 수입가격은 리스트로 작성되어있음 -> np.array로 바꿔줘야함.

# 내가 생각한 방법 ...
# revenue_in_yen = np.array([300000, 340000, 320000, 360000, 
#     440000, 140000, 180000, 340000, 
#     330000, 290000, 280000, 380000, 
#     170000, 140000, 230000, 390000, 
#     400000, 350000, 380000, 150000, 
#     110000, 240000, 380000, 380000, 
#     340000, 420000, 150000, 130000, 
#     360000, 320000, 250000])

# 모범답안 방법
# np.array() 안에는 array를 넣을 수 있다는 점을 생각!! 
yen_array = np.array(revenue_in_yen)

# array로 바꾼 엔화 수입을 환율을 적용해 wonarray에 담기
won_array = yen_array * 10.08

# 테스트 코드
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

### 10. 흥부부대찌개 LA 진출

In [49]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

# 둘 다 array로 바꾸자
yen_array = np.array(revenue_in_yen)
dollar_array = np.array(revenue_in_dollar)

won_array = yen_array*10.08 + dollar_array*1138


# 테스트 코드
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

### 11. numpy 불린 연산

In [50]:
# 냅다 array를 숫자와 비교할 수 있음
# >>> 각 인덱스와 비교해서 True or False를 출력
array1 = np.array([2,3,4,5,6,7,8,9,])
array1 > 4

array([False, False, False,  True,  True,  True,  True,  True])

In [52]:
# 자체 연산하여 불린도 가능 
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False])

In [54]:
# booleans를 넣어두고, False값이 아닌 인덱스만 출력
# where 사용

#### 응용 :: filter(필터링)
- 특정 조건에 맞는 인덱스를 가져와 사용하고 싶을 때

In [55]:
array1 > 4

array([False, False, False,  True,  True,  True,  True,  True])

In [56]:
# 요소의 값이 4이상인 인덱스를 받아와 쓰고 싶다면? 
np.where(array1 > 4) # np.where에 넣어버림

(array([3, 4, 5, 6, 7]),)

In [58]:
# filter에 저장
filter = np.where(array1 > 4)
filter

(array([3, 4, 5, 6, 7]),)

In [61]:
# 그걸 다시 배열에 넣으면
array1[filter] # 인덱스 값으로써 넣음

array([5, 6, 7, 8, 9])

### 12. [실습] 흥부부대찌개 목표 일 매출

In [80]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# array로 바꾸기 (위에는 리스트임)
array_in_yen = np.array(revenue_in_yen)

## "주어진 조건에 해당하는 'filter'를 만들어준다. "
# 매출이 20만엔 이하인 날의 인덱스를 추출
# filter에 그 인덱스 값들의 인덱스를 넣음 (filter는 인덱스 값을 가리킨다.)
filter = np.where(array_in_yen <= 200000)

# bad_days_revenue의 인덱스로서 filter를 삽입
#bad_days_revenue = np.array(array_in_yen[filter])
# bad_days_revenue에 넣는 모범답안
bad_days_revenue = array_in_yen[filter]

##########
# filter 만들지 않고 바로 인덱싱하는 방법
# 어쨋든 filter로 인덱싱을 거르는 거니까. 바로 인덱스에 접근하는 방법도 있음!!
# bad_days_revenue = yen_array[yen_array <= 200000]
##########

# 테스트 코드
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

### 13. numpy array vs. python list

### 왜 numpy array를 사용하는것인가?
- numpy가 방대한 양의 데이터를 빠른속도로 처리할 수 있다.

### <array 와 list의 차이>
#### '저장되는 방식'의 차이
- 파이썬 리스트
    - 다양한 자료형들이 들어갈 수 있음
    - => 값을 추가하고 제거하는 일
- numpy array 
    - 같은 자료형의 값ㄷ르만 들어갈 수 있음
    - => 수치 계산이 많고 복잡할 때
    - => 행렬같은 다차원 배열의 경우 

### 14. numpy 기본 통계

In [81]:
# 최댓값, 최솟값
array1.max()
array1.min()

# 평균값
array1.mean()

# 중앙값 
# median은 numpy array의 메소드가 아니라 numpy의 메소드입니다.
# 짝수개의 요소가 있을 경우 : 중앙값이 두개 -> 둘의 평균값이 중앙값이 된다. 
np.median(array1)

# 표준편차, 분산
# 표준 편차와 분산은 값들이 평균에서 얼마나 떨어져 있는지 나타내는 지표
array1.std()
array1.var() 

9